//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundRequest
    {
        public int Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Information { get; set; }
        public Nullable<int> AmountMoney { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
