//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Idea> Ideas { get; set; }
        public virtual DbSet<AttractionRide> AttractionRides { get; set; }
        public virtual DbSet<Construction> Constructions { get; set; }
        public virtual DbSet<Advertisement> Advertisements { get; set; }
        public virtual DbSet<Maintenence> Maintenences { get; set; }
        public virtual DbSet<PurchaseRequest> PurchaseRequests { get; set; }
        public virtual DbSet<FundRequest> FundRequests { get; set; }
        public virtual DbSet<PersonalRequest> PersonalRequests { get; set; }
        public virtual DbSet<WorkPerformance> WorkPerformances { get; set; }
        public virtual DbSet<PurchaseInformation> PurchaseInformations { get; set; }
        public virtual DbSet<TicketTransaction> TicketTransactions { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
    }
}
